theme: minima

title: Sono in NZ
author: I always welcome your contact in any social media! 
email: 
description: --

twitter_username: uchunchu_mhr
instagram_username: sonoinnz
github_username: Mihiro1ll1

plugins:
    - jekyll-feed
    - jekyll-seo-tag

header_pages: 
    - page/life.md
    - page/jobs.md
    - page/prep.md
    - page/profile.md

minima:
    skin: classic
