#theme: minima
remote_theme: jekyll/minima

title: Sono in NZ
author: --
email: 
description: I always welcome your message in social media!

#twitter_username: mhr1ll1
#instagram_username: sonoinnz
#github_username: Mihiro1ll1

plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-remote-theme
    - jekyll-sitemap

header_pages: 
    - page/work.md
    - page/life.md
    - page/prep.md
    - page/profile.md

minima:
    skin: classic

    social_links:
        - { platform: twitter, user_url: "https://twitter.com/mhr1ll1" }
        #- { platform: x, user_url: "https://x.com/mhr1ll1" }
        - { platform: instagram, user_url: "https://www.instagram.com/sonoinnz" }
        - { platform: github, user_url: "https://github.com/Mihiro1ll1" }

google_analytics: G-BF94NRKD2G
