theme: minima

title: Sono in NZ
author: --
email: 
description: I always welcome you contact me in any social media!

twitter_username: mhr1ll1
instagram_username: sonoinnz
github_username: Mihiro1ll1

plugins:
    - jekyll-seo-tag

header_pages: 
    - page/life.md
    - page/jobs.md
    - page/prep.md
    - page/profile.md

minima:
    skin: classic

google_analytics: G-BF94NRKD2G
