#theme: minima
remote_theme: jekyll/minima

title: Sono in NZ

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages: 
    - page/life.md
    - page/jobs.md
    - page/prep.md
    - page/profile.md

minima:
    skin: classic

    social_links:
        - { platform: instagram, user_url: "https://www.instagram.com/sonoinnz" }
        - { platform: github, user_url: "https://github.com/Mihiro1ll1" }
