services:
    site:
        image: starefossen/github-pages:latest
        volumes:
            - ./:/usr/src/app
        ports:
            - "4000:4000"
        deploy:
            resources:
                limits:
                    cpus: "0.05"
                    memory: 256MB
